# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App

on:
  push:
    branches:
      - master

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using Npm'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          npm run test --if-present
          popd

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .


  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy to Azure Functions App
        uses: Azure/functions-action@v1.5.2
        id: fa
        with:
          app-name: 'exe-dc-bot'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}


  sync-commands:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    - name: Wait For Function App
      run: sleep 60s
      shell: bash

    - name: Send Sync Request
      id: sync-request
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://exe-dc-bot.azurewebsites.net/api/discord/sync'
        method: 'POST'

    - name: Check Commands Synced Correctly
      uses: prompt/actions-assert@v4
      with:
        assertion: npm://@assertions/is-equal:v1
        actual: "${{ steps.sync-request.outputs.status }}"
        expected: 200